### ISSUE TITLE
No examples can be executed. 

### ISSUE THREAD

**Issue by sk413025** [jacobs-robotics/gazebo-mental-simulation#1]
Thank you for sharing your program, it's great learning materials for me. 
I tried to perform examples but there were no any files in world_files/*  and src/*
Does the following repositories do not exist  ?

meta_package_name=gazebo-mental-simulation-meta
"git@github.com: jacobs-robotics / $meta_package_name.git"

**Comment by cheffe112** [comment]
Hello, thanks for pointing this out.

Indeed I haven't included any runnable example yet, but I'm working on an example including a PR2 robot. I added an example meta package and some simulation launch files already.
I'll try to provide an experimental script as soon as possible, hopefully next week. Additionally, I want to enhance the documentation on how to customize the setup to your needs and how to run experiments.

Sorry for delaying this.
Cheers!

**Comment by cheffe112** [comment]
Hello, I've added an example template package which spawns a PR2 environment in some example worlds. 
There is no real business logic other than spawning the environment, however, because this is really application-dependent. Feel free to have a look and check if you can run the experimental script in the complete setup.
Additions and comments are welcome, as well as bug reports.
